steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '--build-arg', '_ACCESS_TOKEN=$_ACCESS_TOKEN', '-t', '$_IMAGE_NAME:$COMMIT_SHA', '.',  '-f', '$_DOCKERFILE_NAME']
    dir: $_DOCKERFILE_DIR
    id: Build
    timeout: "2400s"
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '$_IMAGE_NAME:$COMMIT_SHA']
    id: push
    timeout: "2400s"
  - name: 'gcr.io/cloud-builders/gke-deploy'
    args:
      - prepare
      - '--filename=$_K8S_YAML_PATH'
      - '--image=$_IMAGE_NAME:$COMMIT_SHA'
      - '--app=$_K8S_APP_NAME'
      - '--version=$COMMIT_SHA'
      - '--namespace=$_K8S_NAMESPACE'
      - '--label=$_K8S_LABELS'
      - '--annotation=$_K8S_ANNOTATIONS,gcb-build-id=$BUILD_ID'
      - '--create-application-cr'
      - >-
        --links="Build
        details=https://console.cloud.google.com/cloud-build/builds/$BUILD_ID?project=$PROJECT_ID"
      - '--output=output'
    id: Prepare deploy
    timeout: "2400s"
  - name: gcr.io/cloud-builders/gsutil
    args:
      - '-c'
      - |-
        if [ "$_OUTPUT_BUCKET_PATH" != "" ]
        then
          gsutil cp -r output/suggested gs://$_OUTPUT_BUCKET_PATH/config/$_K8S_APP_NAME/$BUILD_ID/suggested
          gsutil cp -r output/expanded gs://$_OUTPUT_BUCKET_PATH/config/$_K8S_APP_NAME/$BUILD_ID/expanded
        fi
    id: Save configs
    entrypoint: sh
    timeout: "2400s"
  - name: gcr.io/cloud-builders/gke-deploy
    args:
      - apply
      - '--filename=output/expanded'
      - '--cluster=$_GKE_CLUSTER'
      - '--location=$_GKE_LOCATION'
      - '--namespace=$_K8S_NAMESPACE'
    id: Apply deploy
    timeout: "2400s"

timeout: "2400s"
images:
  - '$_IMAGE_NAME:$COMMIT_SHA'
options:
  substitutionOption: ALLOW_LOOSE
  machineType: 'N1_HIGHCPU_8'
substitutions:
  _K8S_APP_NAME: crud-repo-staging
  _GKE_CLUSTER: saral-cluster
  _OUTPUT_BUCKET_PATH: bjp-saral_cloudbuild/deploy
  _DOCKERFILE_DIR: ''
  _K8S_ANNOTATIONS: gcb-trigger-id=770b733e-24d1-4e1d-838a-f8af667d4987
  _K8S_LABELS: ''
  _IMAGE_NAME: gcr.io/bjp-saral/github.com/jarvisconsulting/crud-repo
  _DOCKERFILE_NAME: Dockerfile
  _K8S_NAMESPACE: common
  _K8S_YAML_PATH: kubernetes/staging/
  _GKE_LOCATION: asia-south1-c
tags:
  - gcp-cloud-build-deploy
  - $_K8S_APP_NAME
